"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

The page shell, budget metrics, and Gemini chat are wired for you. Your job is
the ONE function marked `BONUS TODO`: `retrieve_for_case(...)`.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.router import route_query
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CSS = """
<style>
.block-container { padding-top: 2rem; max-width: 1200px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:14px 16px; margin-bottom:12px; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def session_messages(user_id: str, thread_id: str) -> list[dict[str, str]]:
    dataset = load_dataset()
    for user in dataset.get("users", []):
        if user.get("user_id") != user_id:
            continue
        for session in user.get("sessions", []):
            if session.get("thread_id") == thread_id:
                return list(session.get("messages") or [])
    return []


def selected_layers(case: dict[str, Any], has_chat: bool) -> list[str]:
    expected = case.get("expected_layer", "")
    if has_chat:
        layers = ["short_term", *route_query(case.get("query", ""))]
    elif expected == "mixed":
        layers = list(case.get("retrieve_layers") or route_query(case.get("query", "")))
    elif expected in LAYER_COLORS:
        layers = [expected]
    else:
        layers = route_query(case.get("query", ""))

    return list(dict.fromkeys(layers))


def fallback_reply(context: str, reason: str) -> str:
    return (
        f"_{reason} Showing retrieved memory context instead._\n\n"
        + (context[:1800] or "(no memory retrieved)")
    )


def has_any(text: str, terms: tuple[str, ...]) -> bool:
    lowered = text.casefold()
    return any(term.casefold() in lowered for term in terms)


def compose_memory_guide(context: str) -> str:
    has_python = has_any(context, ("Python",))
    has_payment = has_any(context, ("Idempotency-Key", "PAYMENT-RULE-3"))
    has_async_fix = has_any(context, ("ClientSession", "concurrency=20", "ASYNC-FIX-20"))

    if not (has_python and has_payment and has_async_fix):
        return ""

    scope = "Minh"
    if "ORCHID-27" in context:
        scope += " / demo ca nhan ORCHID-27"

    return f"""### Huong dan retry payment scoped cho {scope}

**Scope:** dung cho preference ca nhan cua Minh. Với project cá nhân như ORCHID-27, ưu tiên **Python**. Nếu làm project công ty BLUEBIRD-42 thì phải tách scope vì backend ở đó dùng TypeScript/NestJS.

**Policy payment bat buoc:** moi logical POST payment request phai co cung mot **Idempotency-Key** cho tat ca retry cua request do. Chi retry loi tam thoi nhu HTTP 429 hoac transient 5xx, dung **exponential-backoff**, va dung sau **max-3-retries**. Marker policy: **PAYMENT-RULE-3**.

**Bai hoc async lan truoc:** dung chi tang timeout. Lan truoc fix that su work la reuse **aiohttp ClientSession** va gioi han **concurrency=20**. Reflection: root cause la **connection churn**, khong phai **timeout threshold**. Marker su co: **ASYNC-FIX-20**.

**Cach rap thanh implementation:**

1. Tao mot `Idempotency-Key` cho moi payment intent, roi reuse key do cho moi lan retry.
2. Tao `aiohttp.ClientSession` mot lan cho batch/job, khong tao session moi trong tung retry.
3. Dung `asyncio.Semaphore(20)` de giu concurrency o muc 20.
4. Retry toi da 3 lan cho 429/transient 5xx, moi lan sleep theo exponential backoff.
5. Neu van timeout, kiem tra connection pool, lifecycle cua client va downstream saturation truoc khi nghi den tang timeout.

```python
async with aiohttp.ClientSession() as session:
    sem = asyncio.Semaphore(20)
    headers = {{"Idempotency-Key": payment_key}}
    async with sem:
        # retry POST /payments on 429/transient 5xx with exponential backoff,
        # stop after max-3-retries
        ...
```

Tom lai: voi scope ca nhan cua Minh, hay viet bang Python, tuan thu **Idempotency-Key / PAYMENT-RULE-3**, va giu fix async da work: **ClientSession + concurrency=20** de tranh lap lai **ASYNC-FIX-20**."""


def reply_looks_incomplete(reply: str, context: str) -> bool:
    text = reply.strip()
    if not text:
        return True

    context_has_trio = (
        has_any(context, ("Python",))
        and has_any(context, ("Idempotency-Key", "PAYMENT-RULE-3"))
        and has_any(context, ("ClientSession", "concurrency=20", "ASYNC-FIX-20"))
    )
    if not context_has_trio:
        return False

    required_terms = ("Python", "Idempotency-Key", "ClientSession", "concurrency=20")
    missing_required = [term for term in required_terms if term.casefold() not in text.casefold()]
    if missing_required:
        return True

    dangling_endings = ("là", "và", "của", "ngôn ngữ", "stack", "1.", "2.", "3.", ":")
    return len(text) < 700 or text.casefold().endswith(dangling_endings)


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """BONUS TODO: run student retrieval for the loaded case.

    Return a dict with keys:
      - "merged_context": str  (StudentMemory.assemble_context output)
      - "layers": dict[str, str]  (per-layer evidence: short_term/long_term/
                                   episodic/semantic)
      - "budget": dict  (the breakdown from assemble_context)

    Hints:
      * Build short_term from case["fixture_messages"] if present, else from
        the matching user/thread messages in data/sessions.json, plus
        extra_messages. E01 has no fixture — it uses thread minh-s1.
      * Decide which durable layers to fetch from case["expected_layer"] (or
        case["retrieve_layers"] for "mixed"), then call
        memory.retrieve_long_term / retrieve_episodic / retrieve_semantic.
      * Keep user_id and thread_id from the loaded case.
      * Finish with memory.assemble_context(layers).
    """
    user_id = case["user_id"]
    thread_id = case["thread_id"]
    query = case["query"]
    wanted = selected_layers(case, bool(extra_messages))
    layers = {
        "short_term": "",
        "long_term": "",
        "episodic": "",
        "semantic": "",
    }

    if "short_term" in wanted:
        short_memory = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
        messages = list(case.get("fixture_messages") or session_messages(user_id, thread_id))
        messages.extend(extra_messages)
        for msg in messages:
            short_memory.add(msg["role"], msg["content"])
        layers["short_term"] = short_memory.render()

    if "long_term" in wanted:
        layers["long_term"] = memory.retrieve_long_term(user_id=user_id, thread_id=thread_id, query=query)
    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id=user_id, query=query)
    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(
            graph_id=settings.semantic_graph_id,
            query=query,
        )

    merged_context, budget = memory.assemble_context(layers)
    return {
        "merged_context": merged_context,
        "layers": layers,
        "budget": budget,
    }


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Load a test case, inspect layered retrieval, then keep chatting as that user.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep API key "
                    + ("configured" if zep_ok else "missing"))
        st.markdown(("✅" if gemini_available() else "⚠️") + " Gemini key "
                    + ("configured" if gemini_available() else "missing"))
        st.caption(f"Chat model: `{settings.gemini_model}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Test case", labels)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'<div class="lab-card">{layer_badge(case.get("expected_layer","?"))}'
        f'<b>{case["id"]}</b><br>'
        f'<span class="lab-kv"><b>User:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p style="margin:.5rem 0 0">{case.get("query","")}</p>'
        f'<span class="lab-kv">{case.get("description","")}</span></div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    col_run, _ = st.columns([1, 3])
    if col_run.button("▶️ Run retrieval on this case", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    result = st.session_state.get("last_result")
    if result:
        st.markdown("### 🔎 Retrieved context")
        active = [k for k, v in result["layers"].items() if v.strip()]
        st.markdown(" ".join(layer_badge(k) for k in active) or "_(nothing retrieved)_",
                    unsafe_allow_html=True)

        if result.get("budget"):
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                b = result["budget"].get(layer, {})
                cols[i].metric(
                    layer,
                    f"{b.get('used_tokens', 0)} tok",
                    help=f"limit {b.get('limit_tokens', 0)} · raw {b.get('raw_tokens', 0)}",
                )

        with st.expander("Merged context (budget-trimmed)", expanded=True):
            st.code(result.get("merged_context") or "(empty)", language="markdown")
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f"{name} evidence"):
                    st.write(text)

    st.markdown("### 💬 Continue chat as this user")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Message as this user…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if gemini_available():
                try:
                    reply = generate_reply(context, st.session_state.chat[:-1], prompt)
                    if reply_looks_incomplete(reply, context):
                        reply = (
                            compose_memory_guide(context)
                            or fallback_reply(
                                context,
                                "Gemini returned an incomplete response after generation.",
                            )
                        )
                except Exception as llm_exc:  # noqa: BLE001
                    reply = (
                        compose_memory_guide(context)
                        or fallback_reply(
                            context,
                            "Gemini is temporarily unavailable after retrying.",
                        )
                    )
                    reply += f"\n\n`{type(llm_exc).__name__}: {llm_exc}`"
            else:
                reply = compose_memory_guide(context) or fallback_reply(context, "Gemini key missing.")
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
